### ISSUE TITLE
What program do I use to open this?

### ISSUE THREAD

**Issue by Kushoutthetush** [pajlada/TempestNotifier#1]
Hey, just wondering what I need to use this program?  Ive tried opening it with everything I currently have downloaded and nothing works?

**Comment by pajlada** [comment]
If you go to the releases section, find the latest release and download the
zip file attached. Extract that and run TempestNotifier.exe. I'll type it a
more complete guide tomorrow morning

**Comment by Kushoutthetush** [comment]
Ah, sorry I didnt realize I had to go to the releases section first, working now, thanks a lot for this man!
